# Review python

## generate random array with numpy

In [12]:
import numpy as np
array = np.random.randint(2, size=(4, 5))
print(array)

[[0 0 0 1 0]
 [1 1 0 1 0]
 [0 0 1 0 1]
 [0 0 0 1 0]]


## Return dimension with np.shape or .shape

In [13]:
# return number of col
col = np.shape(array)[1]
print("col =",col)
# return number of row
row = np.shape(array)[0]
print("row =",row)

col = 5
row = 4


## Concatenate array

In [6]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print("axis=1 -> adding row")
print(arr)
print()
print("axis=0 -> adding column")
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

axis=1 -> adding row
[[1 2 5 6]
 [3 4 7 8]]

axis=0 -> adding column
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [8]:
x = np.ones((1,40))*np.linspace(0,1,40)

In [9]:
x

array([[0.        , 0.02564103, 0.05128205, 0.07692308, 0.1025641 ,
        0.12820513, 0.15384615, 0.17948718, 0.20512821, 0.23076923,
        0.25641026, 0.28205128, 0.30769231, 0.33333333, 0.35897436,
        0.38461538, 0.41025641, 0.43589744, 0.46153846, 0.48717949,
        0.51282051, 0.53846154, 0.56410256, 0.58974359, 0.61538462,
        0.64102564, 0.66666667, 0.69230769, 0.71794872, 0.74358974,
        0.76923077, 0.79487179, 0.82051282, 0.84615385, 0.87179487,
        0.8974359 , 0.92307692, 0.94871795, 0.97435897, 1.        ]])

In [1]:
for i in range(0,3):
    print(i)

0
1
2


3. Know the unique value in the last column

In [15]:
# Assuming 'data' is your NumPy array or list
last_column = array[:, -1]  # Extract the last column
unique_values = np.unique(last_column)
print(unique_values)

[0 1]


So you may ask, why do we use -1?
if we use 1 it will be the first column. the last column will be either 4 or -1.

# Common np methods

Certainly! Let's go over each method one by one with Python code examples:

1. `np.array()`: Create an array from a list or tuple.

In [29]:
import numpy as np

lst = [1, 2, 3]
arr = np.array(lst)
print(arr)  # Output: [1 2 3]

[1 2 3]


2. `np.zeros()`: Create an array filled with zeros.

In [30]:
import numpy as np

shape = (2, 3)
arr = np.zeros(shape)
print(arr)
# Output:
# [[0. 0. 0.]
#  [0. 0. 0.]]

[[0. 0. 0.]
 [0. 0. 0.]]


3. `np.ones()`: Create an array filled with ones.


In [31]:
import numpy as np

shape = (3, 3)
arr = np.ones(shape)
print(arr)
# Output:
# [[1. 1. 1.]
#  [1. 1. 1.]
#  [1. 1. 1.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


4. `np.empty()`: Create an empty array.


In [32]:
import numpy as np

shape = (2, 2)
arr = np.empty(shape)
print(arr)
# Output:
# [[2.12199579e-314 2.12199579e-314]
#  [0.00000000e+000 0.00000000e+000]]

[[0.25 0.5 ]
 [0.75 1.  ]]


5. `np.arange()`: Create an array with evenly spaced values.


In [33]:
import numpy as np

start = 0
stop = 10
step = 2
arr = np.arange(start, stop, step)
print(arr)  # Output: [0 2 4 6 8]

[0 2 4 6 8]


6. `np.linspace()`: Create an array with evenly spaced values over a range.

In [34]:
import numpy as np

start = 0
stop = 1
num = 5
arr = np.linspace(start, stop, num)
print(arr)
# Output: [0.   0.25 0.5  0.75 1.  ]

[0.   0.25 0.5  0.75 1.  ]


7. `np.random.rand()`: Create an array of random values.

In [35]:
import numpy as np

shape = (3, 3)
arr = np.random.rand(shape[0], shape[1])
print(arr)  # Output: Randomly generated array

[[0.48359018 0.06173915 0.21093998]
 [0.58681239 0.08397399 0.45981016]
 [0.04479783 0.5248001  0.23691481]]


8. `ndarray.shape`: Get the dimensions of an array.


In [36]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
shape = arr.shape
print(shape)  # Output: (2, 3)

(2, 3)


9. `ndarray.reshape()`: Reshape an array.


In [37]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
new_shape = (2, 3)
reshaped_arr = arr.reshape(new_shape)
print(reshaped_arr)  # Output: Reshaped array

[[1 2 3]
 [4 5 6]]


10. `ndarray.ndim`: Get the number of array dimensions.


In [38]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
ndim = arr.ndim
print(ndim)  # Output: 2

2


11. `ndarray.size`: Get the total number of elements in an array.


In [39]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
size = arr.size
print

(size)  # Output: 6

6

12. `np.add()`: Add two arrays element-wise.


In [40]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.add(arr1, arr2)
print(result)  # Output: [5 7 9]

[5 7 9]


13. `np.subtract()`: Subtract one array from another element-wise.


In [41]:
import numpy as np

arr1 = np.array([4, 5, 6])
arr2 = np.array([1, 2, 3])
result = np.subtract(arr1, arr2)
print(result)  # Output: [3 3 3]

[3 3 3]


14. `np.multiply()`: Multiply two arrays element-wise.


In [42]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.multiply(arr1, arr2)
print(result)  # Output: [4 10 18]

[ 4 10 18]


15. `np.divide()`: Divide elements of one array by another element-wise.


In [43]:
import numpy as np

arr1 = np.array([4, 10, 18])
arr2 = np.array([2, 5, 3])
result = np.divide(arr1, arr2)
print(result)  # Output: [2. 2. 6.]

[2. 2. 6.]


16. `ndarray[start:end:step]`: Extract a portion of the array with a step size.


In [44]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:5:2]
print(sub_arr)  # Output: [2 4]

[2 4]


17. `ndarray[condition]`: Use a condition to select specific elements from the array.


In [45]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[arr > 3]
print(sub_arr)  # Output: [4 5]

[4 5]


18. `ndarray[:, col_index]`: Access a specific column in a multi-dimensional array.


In [46]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
col_arr = arr[:, 2]
print(col_arr)  # Output: [3 6]

[3 6]


19. `np.meshgrid()`: Create coordinate matrices from coordinate vectors.


In [53]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 4, 7])
X, Y = np.meshgrid(x, y)
print(X)
print()
print(Y)
# Output:
# [[1 2 3]
#  [1 2 3]]
# [[4 4 4]
#  [5 5 5]]

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]

[[4 4 4]
 [5 5 5]
 [4 4 4]
 [7 7 7]]


20. `np.stack()`: Stack arrays along a new axis.


In [51]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([4, 5, 6, 3])
stacked_arr = np.stack((arr1, arr2))
print(stacked_arr)
# Output:
# [[1 2 3]
#  [4 5 6]]

[[1 2 3 4]
 [4 5 6 3]]
